### ISSUE TITLE
Preferences not displaying when clicked.

### ISSUE THREAD

**Issue by mr-anji** [flathub/io.github.TanmayPatil105.verse#2]
Issue:
```
$ flatpak run io.github.TanmayPatil105.verse
Traceback (most recent call last):
  File "/app/share/verse/verse/main.py", line 64, in on_preferences_action
    self.preferences_window = VersePreferences()
                              ^^^^^^^^^^^^^^^^^^
  File "/app/share/verse/verse/views/verse_preferences.py", line 47, in __init__
    self.update_widgets()
  File "/app/share/verse/verse/views/verse_preferences.py", line 101, in update_widgets
    secrets = retrieve_secrets()
              ^^^^^^^^^^^^^^^^^^
  File "/app/share/verse/verse/lib/secrets.py", line 49, in retrieve_secrets
    password = Secret.password_lookup_sync(SECRET_SCHEMA, {}, None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: org.freedesktop.DBus.Error.ServiceUnknown (2)
```

**Comment by TanmayPatil105** [comment]
Hi, I've been trying to figure out this bug.
Meanwhile, If possible can you try building verse locally using Builder? Instructions: [builder](https://github.com/TanmayPatil105/verse/?tab=readme-ov-file#build-using-gnome-builder)

**Comment by TanmayPatil105** [comment]
Hey @mr-anji,
I think I have a fix: https://github.com/TanmayPatil105/verse/commit/300a364db6dfa2bd4d6ab567887bf478481848c7.
Can you test, if that's correct?

```
$ flatpak-builder  --force-clean _flatpak/ io.github.TanmayPatil105.verse.json  --user --install
$ flatpak run io.github.TanmayPatil105.verse
```

**Comment by TanmayPatil105** [comment]
Closing
See https://github.com/TanmayPatil105/verse/issues/2
